# Setup
title: Joseph Han
url: https://sugoijosephhan2627.github.io
paginate: 2
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: SugoiJosephHan2627
  url: https://weibo.com/SugoiJosephHan2627
  email: SugoiJosephHan2627@outlook.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: 主页
    url: /
    
  - title: 博客
    url: /archive

  - title: 关于
    url: /about
  
  - title: 微博
    url: https://weibo.com/SugoiJosephHan2627

  - title: English
    url: /404.html
